using System.Text.Json;
using Jellyfin.Plugin.AoideSidecar.Next;
using Jellyfin.Plugin.AoideSidecar.Sound;
using Xunit;

namespace Jellyfin.Plugin.AoideSidecar.Tests;

/// <summary>
/// The clients' fixture for <c>/aoide/next</c>, byte for byte: twenty records, sixteen
/// decided listens on a fixed clock, one flag, and seven requests with every candidate's
/// score and factors to six decimals, in order.
/// </summary>
/// <remarks>
/// The same file is read by the phone (<c>NextRankingFixtureTests</c>) and the desktop
/// (<c>next-ranking-fixture.test.ts</c>). It was generated by the phone's reference,
/// passes an independent TypeScript port, has four rows worked by hand against the
/// contract's prose, and fails seventeen mutations of the rule. A row this port scores
/// differently names the rule that differs.
/// </remarks>
public sealed class NextRankingFixtureTests
{
    private static readonly Lazy<Fixture> Loaded = new(Load);

    public static IEnumerable<object[]> Cases() => Enumerable.Range(0, Loaded.Value.Cases.Count).Select(i => new object[] { i });

    [Theory]
    [MemberData(nameof(Cases))]
    public void Ranks_the_clients_fixture_identically(int index)
    {
        var fixture = Loaded.Value;
        var test = fixture.Cases[index];

        var request = new NextRequest(test.Seed, test.Queue, test.Recent, test.Mode == "autodj", test.Limit);
        var result = NextRanker.Rank(request, fixture.Library, fixture.Plays, fixture.NotInterested, fixture.Measured, fixture.Now);

        Assert.True(result.ProfileEvents == test.Events, $"{test.Name}: events {result.ProfileEvents}, expected {test.Events}");
        Assert.True(
            result.Candidates.Count == test.Expected.Count,
            $"{test.Name}: {result.Candidates.Count} candidates, expected {test.Expected.Count}: [{string.Join(", ", result.Candidates.Select(c => c.Id))}]");

        for (var i = 0; i < test.Expected.Count; i++)
        {
            var got = result.Candidates[i];
            var want = test.Expected[i];
            Assert.True(got.Id == want.Id, $"{test.Name}: position {i} is {got.Id}, expected {want.Id}");
            Assert.True(Rounded(got.Score) == Rounded(want.Score), $"{test.Name}: {got.Id} scored {got.Score}, expected {want.Score}");
            Assert.True(Rounded(got.Factors.Taste) == Rounded(want.Taste), $"{test.Name}: {got.Id} taste {got.Factors.Taste}, expected {want.Taste}");
            Assert.True(Rounded(got.Factors.Freshness) == Rounded(want.Freshness), $"{test.Name}: {got.Id} freshness {got.Factors.Freshness}, expected {want.Freshness}");
            Assert.True(Rounded(got.Factors.Similarity) == Rounded(want.Similarity), $"{test.Name}: {got.Id} similarity {got.Factors.Similarity}, expected {want.Similarity}");
            Assert.True(Rounded(got.Factors.Arc) == Rounded(want.Arc), $"{test.Name}: {got.Id} arc {got.Factors.Arc}, expected {want.Arc}");
            Assert.True(
                (got.Factors.Mixability is null) == (want.Mixability is null)
                && (got.Factors.Mixability is null || Rounded(got.Factors.Mixability.Value) == Rounded(want.Mixability!.Value)),
                $"{test.Name}: {got.Id} mixability {got.Factors.Mixability}, expected {want.Mixability}");
        }
    }

    [Fact]
    public void Answers_every_case_in_the_fixture()
    {
        Assert.Equal(7, Loaded.Value.Cases.Count);
        Assert.Equal(20, Loaded.Value.Library.Count);
        Assert.Equal(16, Loaded.Value.Plays.Count);
    }

    private static double Rounded(double value) => Math.Round(value * 1_000_000) / 1_000_000;

    private static Fixture Load()
    {
        var path = Path.Combine(AppContext.BaseDirectory, "Fixtures", "next-ranking-fixture.json");
        using var document = JsonDocument.Parse(File.ReadAllText(path));
        var root = document.RootElement;

        var library = new List<LibraryTrack>();
        var measured = new Dictionary<string, Measured>(StringComparer.OrdinalIgnoreCase);
        foreach (var record in root.GetProperty("library").EnumerateArray())
        {
            var id = record.GetProperty("id").GetString()!;
            var genres = record.TryGetProperty("genres", out var g) && g.ValueKind == JsonValueKind.Array
                ? g.EnumerateArray().Select(x => x.GetString()!).ToList()
                : new List<string>();
            library.Add(new LibraryTrack(id, record.GetProperty("artist").GetString()!, genres));

            Tempo? tempo = record.TryGetProperty("bpm", out var bpm) && bpm.ValueKind == JsonValueKind.Number
                ? new Tempo(
                    bpm.GetDouble(),
                    1,
                    record.TryGetProperty("bpmStability", out var st) && st.ValueKind == JsonValueKind.Number ? st.GetDouble() : null)
                : null;
            var key = record.TryGetProperty("key", out var k) && k.ValueKind == JsonValueKind.String ? k.GetString() : null;
            Arrangement? arrangement = record.TryGetProperty("sections", out var sections) && sections.ValueKind == JsonValueKind.Array
                ? new Arrangement(
                    sections.EnumerateArray().Select(s => new Section(
                        s.GetProperty("startMs").GetDouble(),
                        s.GetProperty("endMs").GetDouble(),
                        SectionKind.Unknown,
                        s.GetProperty("energy").GetDouble())).ToList(),
                    null, null, null)
                : null;
            measured[id] = new Measured(tempo, null, key, arrangement);
        }

        var plays = root.GetProperty("plays").EnumerateArray().Select(p => new PlayEvent(
            p.GetProperty("id").GetString()!,
            p.GetProperty("startedAt").GetInt64(),
            null,
            p.GetProperty("completed").GetBoolean(),
            p.GetProperty("skipped").GetBoolean())).ToList();

        var notInterested = root.GetProperty("notInterested").EnumerateArray().Select(x => x.GetString()!).ToHashSet(StringComparer.OrdinalIgnoreCase);

        var cases = root.GetProperty("cases").EnumerateArray().Select(c => new Case(
            c.GetProperty("name").GetString()!,
            c.GetProperty("seed").GetString()!,
            c.GetProperty("queue").EnumerateArray().Select(x => x.GetString()!).ToList(),
            c.GetProperty("recent").EnumerateArray().Select(x => x.GetString()!).ToList(),
            c.GetProperty("mode").GetString()!,
            c.GetProperty("limit").GetInt32(),
            c.GetProperty("expected").GetProperty("events").GetInt32(),
            c.GetProperty("expected").GetProperty("candidates").EnumerateArray().Select(e =>
            {
                var f = e.GetProperty("factors");
                return new Expected(
                    e.GetProperty("id").GetString()!,
                    e.GetProperty("score").GetDouble(),
                    f.GetProperty("taste").GetDouble(),
                    f.GetProperty("freshness").GetDouble(),
                    f.GetProperty("similarity").GetDouble(),
                    f.GetProperty("mixability").ValueKind == JsonValueKind.Null ? null : f.GetProperty("mixability").GetDouble(),
                    f.GetProperty("arc").GetDouble());
            }).ToList())).ToList();

        return new Fixture(root.GetProperty("now").GetInt64(), library, measured, plays, notInterested, cases);
    }

    private sealed record Fixture(
        long Now,
        IReadOnlyList<LibraryTrack> Library,
        IReadOnlyDictionary<string, Measured> Measured,
        IReadOnlyList<PlayEvent> Plays,
        IReadOnlySet<string> NotInterested,
        IReadOnlyList<Case> Cases);

    private sealed record Case(string Name, string Seed, IReadOnlyList<string> Queue, IReadOnlyList<string> Recent, string Mode, int Limit, int Events, IReadOnlyList<Expected> Expected);

    private sealed record Expected(string Id, double Score, double Taste, double Freshness, double Similarity, double? Mixability, double Arc);
}
